# Generated by Django 3.0.6 on 2020-08-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allshirts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allshirts',
            name='img',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
