# Generated by Django 3.0.6 on 2020-08-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allshirts', '0002_auto_20200830_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allshirts',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
