# Generated by Django 3.0.6 on 2020-09-12 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0003_auto_20200912_0102'),
        ('allshirts', '0003_auto_20200830_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('size', models.CharField(max_length=5)),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('shirt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allshirts.allshirts')),
            ],
        ),
    ]
