# Generated by Django 3.0.6 on 2020-09-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='refund',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
