# Generated by Django 3.0.6 on 2020-09-12 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200907_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shirt_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
    ]
