# Generated by Django 3.0.6 on 2020-12-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200912_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
